name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Build jupyterlite
        run: |
          python -m pip install -r requirements.txt
          jupyter lite build --contents content --output-dir dist

      - name: Build the JupyterLite site
        run: |
          cp README.md content
          cp -r ./packages_wasmbuilt/ ./files/
          jupyter lite build --contents content --output-dir dist
          cp -r ./packages_wasmbuilt/ dist/repo/
          cp -r ./webr-dist/ dist/webr-dist/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist